---
- hosts: 13.215.194.130
  become: yes
  tasks:
    - name: Checking if apache2 is available.
      apt:
        name: apache2
        update_cache: yes
        state: latest
        
    - name: Copying files to /backup
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 80"
        line: "Listen 8080"
      notify:
        - restart apache2
        
    - name: Update apache2 file
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 8080"
        line: "Listen 8081"
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
